# Generated by Django 3.0.8 on 2020-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250, verbose_name='Name')),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_amount', models.PositiveIntegerField(default='0', null=True, verbose_name='Monto')),
                ('client_id', models.PositiveIntegerField(default='0', null=True, verbose_name='Id cliente')),
                ('client_name', models.CharField(max_length=100, verbose_name='client_name')),
            ],
        ),
    ]
