# Generated by Django 3.0.8 on 2020-07-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0002_archivo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='name',
            field=models.FileField(max_length=250, upload_to='', verbose_name='Name'),
        ),
    ]
