# Generated by Django 3.0.8 on 2020-07-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0003_auto_20200703_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
