# Generated by Django 3.0.8 on 2020-07-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0006_auto_20200703_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='transaction_amount',
            field=models.CharField(max_length=250, null=True, verbose_name='Monto'),
        ),
    ]
