# Generated by Django 3.0.8 on 2020-07-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0007_auto_20200703_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='client_id',
            field=models.CharField(max_length=250, null=True, verbose_name='Id cliente'),
        ),
    ]
