# Generated by Django 3.0.8 on 2020-07-04 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0008_auto_20200703_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='archivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaccion.Archivo', verbose_name='User'),
        ),
    ]
